name: Action | Deploy to FAKE Production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npx lerna bootstrap --scope=@soonaverse/ui
      - name: Build
        run: npm run build
      # enable maintenance mode.
      - name: Enable maintenance mode
        run: |
          cd dist
          # Remove all other files.
          ls | grep -v maintenance.html | xargs rm -fr
          mv maintenance.html index.html
      # End of maintenance mode.
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOONAVERSE }}'
          projectId: 'soonaverse'
          channelId: live
          target: def-host
